export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_ACCESS = "AUTH_LOGIN_ACCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_LOGOUT = "AUTH_LOGIN_LOGOUT";

// Test
export const TEST_SUM = "TEST_SUM";
